-- Phase 1: case tracking + audit (matches FRAUD_COPILOT.DEMO TXN_ID schema)

USE DATABASE FRAUD_COPILOT;
USE SCHEMA DEMO;

CREATE TABLE IF NOT EXISTS CASES (
    CASE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    TXN_ID STRING NOT NULL,
    STATUS STRING NOT NULL DEFAULT 'OPEN',
    PRIORITY STRING DEFAULT 'MEDIUM',
    RECOMMENDATION STRING,
    RISK_SCORE NUMBER(5,2),
    NEXT_ACTIONS VARIANT,
    OPENED_BY STRING DEFAULT CURRENT_USER(),
    OPENED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE STRING DEFAULT 'STREAMLIT_PHASE1'
);

CREATE TABLE IF NOT EXISTS CASE_EVENTS (
    EVENT_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CASE_ID NUMBER,
    TXN_ID STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_DATA VARIANT,
    ACTOR STRING DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Optional: seed empty open cases for flagged txns (no risk columns on TRANSACTIONS)
INSERT INTO CASES (TXN_ID, STATUS, PRIORITY, RECOMMENDATION, RISK_SCORE, NEXT_ACTIONS, OPENED_BY, SOURCE)
SELECT DISTINCT
    t.TXN_ID,
    'OPEN',
    'MEDIUM',
    NULL,
    NULL,
    PARSE_JSON('["Review in Streamlit / CoCo","Open case after scoring"]'),
    'PHASE1_SEED',
    'SQL_SEED'
FROM TRANSACTIONS t
WHERE UPPER(t.STATUS) = 'FLAGGED'
  AND NOT EXISTS (
      SELECT 1 FROM CASES c
      WHERE c.TXN_ID = t.TXN_ID AND c.STATUS NOT IN ('CLOSED', 'CANCELLED')
  );

INSERT INTO CASE_EVENTS (CASE_ID, TXN_ID, EVENT_TYPE, EVENT_DATA, ACTOR)
SELECT
    c.CASE_ID,
    c.TXN_ID,
    'CASE_OPENED',
    OBJECT_CONSTRUCT('source', c.SOURCE),
    c.OPENED_BY
FROM CASES c
WHERE c.SOURCE = 'SQL_SEED'
  AND NOT EXISTS (
      SELECT 1 FROM CASE_EVENTS e
      WHERE e.CASE_ID = c.CASE_ID AND e.EVENT_TYPE = 'CASE_OPENED'
  );
