-- Phase 1b: per-run audit log + Snowflake Alert on high-risk reviews
USE DATABASE FRAUD_COPILOT;
USE SCHEMA DEMO;

CREATE TABLE IF NOT EXISTS REVIEW_AUDIT (
  AUDIT_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  TXN_ID STRING NOT NULL,
  RISK_SCORE NUMBER(5,2),
  RECOMMENDATION STRING,
  FIRED_RULES VARIANT,
  SOURCE STRING DEFAULT 'STREAMLIT',
  REVIEWED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  REVIEWED_BY STRING DEFAULT CURRENT_USER()
);

-- View: latest high-risk reviews in the last 24h (alert condition source)
CREATE OR REPLACE VIEW HIGH_RISK_REVIEWS_24H AS
SELECT *
FROM REVIEW_AUDIT
WHERE RISK_SCORE >= 70
  AND REVIEWED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP());

-- Optional notification integration (email) — create only if you have a verified email
-- CREATE OR REPLACE NOTIFICATION INTEGRATION IF NOT EXISTS fraud_email_int
--   TYPE = EMAIL ENABLED = TRUE ALLOWED_RECIPIENTS = ('suhail39ahmed@gmail.com');

-- Serverless Alert: fires when any high-risk review exists in last hour
-- Requires ACCOUNTADMIN. If Alert unsupported on trial, keep the VIEW + Task fallback below.
CREATE OR REPLACE ALERT FRAUD_HIGH_RISK_ALERT
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '60 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM REVIEW_AUDIT
    WHERE RISK_SCORE >= 70
      AND REVIEWED_AT >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
  ))
  THEN
    INSERT INTO CASE_EVENTS (CASE_ID, TXN_ID, EVENT_TYPE, EVENT_DATA, ACTOR)
    SELECT
      NULL,
      a.TXN_ID,
      'ALERT_HIGH_RISK',
      OBJECT_CONSTRUCT(
        'risk_score', a.RISK_SCORE,
        'recommendation', a.RECOMMENDATION,
        'reviewed_at', a.REVIEWED_AT
      ),
      'FRAUD_HIGH_RISK_ALERT'
    FROM REVIEW_AUDIT a
    WHERE a.RISK_SCORE >= 70
      AND a.REVIEWED_AT >= DATEADD('hour', -1, CURRENT_TIMESTAMP());

ALTER ALERT FRAUD_HIGH_RISK_ALERT RESUME;

-- Fallback Task if CREATE ALERT fails on your account:
-- CREATE OR REPLACE TASK FRAUD_HIGH_RISK_TASK
--   WAREHOUSE = COMPUTE_WH
--   SCHEDULE = '60 MINUTE'
-- AS
--   INSERT INTO CASE_EVENTS (CASE_ID, TXN_ID, EVENT_TYPE, EVENT_DATA, ACTOR)
--   SELECT NULL, TXN_ID, 'ALERT_HIGH_RISK',
--          OBJECT_CONSTRUCT('risk_score', RISK_SCORE, 'recommendation', RECOMMENDATION),
--          'FRAUD_HIGH_RISK_TASK'
--   FROM REVIEW_AUDIT
--   WHERE RISK_SCORE >= 70
--     AND REVIEWED_AT >= DATEADD('hour', -1, CURRENT_TIMESTAMP());
-- ALTER TASK FRAUD_HIGH_RISK_TASK RESUME;
