-- Phase 2: fraud-ring graph attributes + views (no external APIs)
-- Schema: FRAUD_COPILOT.DEMO
-- Demo seeds: C003+C005 share DEVICE_ID; C002+C005 share IBAN_LAST4

USE DATABASE FRAUD_COPILOT;
USE SCHEMA DEMO;

CREATE TABLE IF NOT EXISTS CUSTOMER_GRAPH_ATTRS (
    CUSTOMER_ID     STRING NOT NULL,
    DEVICE_ID       STRING,
    IBAN_LAST4      STRING,
    SHARED_PHONE    STRING,
    MERCHANT_CLUSTER STRING,
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_ID)
);

-- Seed demo graph attrs (MERGE so re-runs are idempotent)
MERGE INTO CUSTOMER_GRAPH_ATTRS t
USING (
    SELECT COLUMN1 AS CUSTOMER_ID,
           COLUMN2 AS DEVICE_ID,
           COLUMN3 AS IBAN_LAST4,
           COLUMN4 AS SHARED_PHONE,
           COLUMN5 AS MERCHANT_CLUSTER
    FROM VALUES
        ('C001', 'DEV-A100', '4412', '+971-500-0001', 'CLUSTER_RETAIL'),
        ('C002', 'DEV-B200', '7789', '+971-500-0002', 'CLUSTER_TRAVEL'),
        -- C003 and C005 share DEVICE_ID = DEV-RING-01
        ('C003', 'DEV-RING-01', '3301', '+971-500-0003', 'CLUSTER_CRYPTO'),
        ('C004', 'DEV-C400', '5500', '+971-500-0004', 'CLUSTER_RETAIL'),
        -- C005 shares DEVICE with C003; shares IBAN_LAST4 7789 with C002
        ('C005', 'DEV-RING-01', '7789', '+971-500-0005', 'CLUSTER_CRYPTO')
) s
ON t.CUSTOMER_ID = s.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    DEVICE_ID = s.DEVICE_ID,
    IBAN_LAST4 = s.IBAN_LAST4,
    SHARED_PHONE = s.SHARED_PHONE,
    MERCHANT_CLUSTER = s.MERCHANT_CLUSTER,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ID, DEVICE_ID, IBAN_LAST4, SHARED_PHONE, MERCHANT_CLUSTER
) VALUES (
    s.CUSTOMER_ID, s.DEVICE_ID, s.IBAN_LAST4, s.SHARED_PHONE, s.MERCHANT_CLUSTER
);

-- Undirected edges: one row per pair (src < dst) per shared key
CREATE OR REPLACE VIEW V_FRAUD_RING_EDGES AS
WITH attrs AS (
    SELECT CUSTOMER_ID, DEVICE_ID, IBAN_LAST4, SHARED_PHONE, MERCHANT_CLUSTER
    FROM CUSTOMER_GRAPH_ATTRS
)
SELECT a.CUSTOMER_ID AS SRC_CUSTOMER,
       b.CUSTOMER_ID AS DST_CUSTOMER,
       'SHARED_DEVICE' AS EDGE_TYPE,
       a.DEVICE_ID AS EDGE_KEY
FROM attrs a
JOIN attrs b
  ON a.DEVICE_ID = b.DEVICE_ID
 AND a.DEVICE_ID IS NOT NULL
 AND a.CUSTOMER_ID < b.CUSTOMER_ID
UNION ALL
SELECT a.CUSTOMER_ID, b.CUSTOMER_ID, 'SHARED_IBAN_LAST4', a.IBAN_LAST4
FROM attrs a
JOIN attrs b
  ON a.IBAN_LAST4 = b.IBAN_LAST4
 AND a.IBAN_LAST4 IS NOT NULL
 AND a.CUSTOMER_ID < b.CUSTOMER_ID
UNION ALL
SELECT a.CUSTOMER_ID, b.CUSTOMER_ID, 'SHARED_PHONE', a.SHARED_PHONE
FROM attrs a
JOIN attrs b
  ON a.SHARED_PHONE = b.SHARED_PHONE
 AND a.SHARED_PHONE IS NOT NULL
 AND a.CUSTOMER_ID < b.CUSTOMER_ID
UNION ALL
SELECT a.CUSTOMER_ID, b.CUSTOMER_ID, 'SHARED_MERCHANT_CLUSTER', a.MERCHANT_CLUSTER
FROM attrs a
JOIN attrs b
  ON a.MERCHANT_CLUSTER = b.MERCHANT_CLUSTER
 AND a.MERCHANT_CLUSTER IS NOT NULL
 AND a.CUSTOMER_ID < b.CUSTOMER_ID;

-- Nodes: customers with graph attrs + optional customer profile fields
CREATE OR REPLACE VIEW V_FRAUD_RING_NODES AS
SELECT
    g.CUSTOMER_ID,
    c.FULL_NAME,
    c.COUNTRY,
    c.RISK_TIER,
    c.ACCOUNT_TYPE,
    g.DEVICE_ID,
    g.IBAN_LAST4,
    g.SHARED_PHONE,
    g.MERCHANT_CLUSTER,
    (
        SELECT COUNT(*)
        FROM V_FRAUD_RING_EDGES e
        WHERE e.SRC_CUSTOMER = g.CUSTOMER_ID OR e.DST_CUSTOMER = g.CUSTOMER_ID
    ) AS EDGE_COUNT
FROM CUSTOMER_GRAPH_ATTRS g
LEFT JOIN CUSTOMERS c ON c.CUSTOMER_ID = g.CUSTOMER_ID;

-- Quick verify (optional):
-- SELECT * FROM V_FRAUD_RING_EDGES ORDER BY EDGE_TYPE, SRC_CUSTOMER;
-- Expect: C003–C005 SHARED_DEVICE DEV-RING-01; C002–C005 SHARED_IBAN_LAST4 7789
